image: node:22

stages:
  - install
  - build
  - release

variables:
  GITLAB_TOKEN: $GIT_AUTH_TOKEN
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: true
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

cache:
  paths:
    - node_modules/
    - .yarn/cache/

install_dependencies:
  stage: install
  before_script:
    - corepack enable
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

build_app:
  stage: build
  before_script:
    - corepack enable
  script:
    - apt install jq --no-install-recommends -y
    - RELEASE_TAG="release-$(date +%Y%m%d%H%M%S)"
    - git submodule update --init --recursive
    - yarn run web:build:prod
    - cd extensions 
    - sh build_extensions.sh 
    - cp -r release ../web/.webpack/extensions
    - rm -r release
    - cd ..
    - tar -czf $RELEASE_TAG.tar.gz -C web/.webpack .
  artifacts:
    paths:
      - $RELEASE_TAG.tar.gz
    expire_in: 1 hour

release_app:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  needs:
    - job: build_app
      artifacts: true
  script:
    - RELEASE_TAG="release-$(date +%Y%m%d%H%M%S)"
    - RELEASE_NAME="Release $(date "+%Y-%m-%d %H:%M:%S")"
    - echo "Creating $RELEASE_TAG"
    - glab auth login --job-token "$CI_JOB_TOKEN" --hostname "$CI_SERVER_HOST"
    - glab config set telemetry false
    - glab release create $RELEASE_TAG --name "$RELEASE_NAME" --notes "Automated release created at $(date "+%Y-%m-%d %H:%M:%S")" $RELEASE_TAG.tar.gz

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
